# 1 2 - Jack
# 3 4 5 - Jayden
Explain why we chose a given algorithm not how the algorithm works

In [15]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from utils import read_classification_dataset, features_histograms_mean_std
# import sklearn
from sklearnex import patch_sklearn
from sklearn.calibration import LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report,ConfusionMatrixDisplay
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.model_selection import cross_val_score
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer, SimpleImputer, KNNImputer
from sklearn.decomposition import PCA
from sklearn.model_selection import GridSearchCV

from kneed import KneeLocator

patch_sklearn()


Intel(R) Extension for Scikit-learn* enabled (https://github.com/intel/scikit-learn-intelex)


In [16]:
# KNN Scores
knn = Pipeline(
    [
        ('Scaler', MinMaxScaler(feature_range=(0, 1))),
        ('Imputer', KNNImputer(n_neighbors=3, weights='distance')),
        ('KNN', KNeighborsClassifier(3, weights='distance',)),
    ]
)
def test_model_on_all_data(model, data:list=list(range(1,6))):
    predicitons = []
    for i in data:
        try:
            train, target, test = read_classification_dataset(i)
            X, y = train.values, target.values.flatten()
            score = cross_val_score(model, X, y,scoring='f1_weighted', cv=5)
            print(f"dataset {i} weighted F1 score 5 fold cv: ",score)
            score.sort()
            print(f"mean: {score.mean():.3f}", )
            print(f"median: {score[len(score)//2+1]:.3f}", )
            print(f"std: {score.std():.3f}", )

            predicitons.append(model.fit(train, np.ravel(target)).predict(test.values))

        except ValueError as e:
            print(e)
    return predicitons

def test_model_on_data(model, data_set_number:int):
    try:
        train, target, test = read_classification_dataset(data_set_number)
        X, y = train.values, target.values.flatten()
        score = cross_val_score(model, X, y,scoring='f1_weighted', cv=5)
        print(f"dataset {data_set_number} weighted F1 score 5 fold cv: ",score)
        predicitons = model.fit(train, np.ravel(target)).predict(test.values)
        return predicitons

    except ValueError as e:
        print(e)

test_model_on_all_data(knn)

    # else:
    #     display(train.dtypes)
    #     display(train.head())

c:\Users\Morri\Documents\Notebooks\ML\Project


c:\Users\Morri\Documents\Notebooks\ML\.venv\Lib\site-packages\sklearn\model_selection\_split.py:737: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(


dataset 1 weighted F1 score 5 fold cv:  [1.         0.96866002 0.89555556 0.91262626 0.9503876 ]
mean: 0.945
median: 0.969
std: 0.038
c:\Users\Morri\Documents\Notebooks\ML\Project
dataset 2 weighted F1 score 5 fold cv:  [0.93       0.89666667 0.84666667 0.58666667 0.83333333]
mean: 0.819
median: 0.897
std: 0.121
c:\Users\Morri\Documents\Notebooks\ML\Project
dataset 3 weighted F1 score 5 fold cv:  [0.27594564 0.24559458 0.28446243 0.26068096 0.26436301]
mean: 0.266
median: 0.276
std: 0.013
c:\Users\Morri\Documents\Notebooks\ML\Project
dataset 4 weighted F1 score 5 fold cv:  [0.8001186  0.65752045 0.64975154 0.56101407 0.42992551]
mean: 0.620
median: 0.658
std: 0.122
c:\Users\Morri\Documents\Notebooks\ML\Project
dataset 5 weighted F1 score 5 fold cv:  [0.41752807 0.48990801 0.50588167 0.48642254 0.53146975]
mean: 0.486
median: 0.506
std: 0.038


[array([2, 1, 1, 1, 1, 2, 1, 1, 3, 1, 3, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 4,
        3, 3, 4, 1, 5, 4, 1, 3, 1, 1, 4, 1, 1, 1, 1, 4, 3, 5, 3, 1, 4, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64),
 array([ 3, 11,  2,  4,  8,  8,  8,  8,  4,  8, 10, 11,  1,  1, 10,  8,  6,
         3,  8,  9,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4, 10, 11, 10, 11,
         4, 10, 11,  3,  3,  3,  3,  3,  3,  3,  2,  8,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  8,  8,  8,  8,  8,  8,  8,  8,
        11,  8, 10,  8,  8,  8], dtype=int64),
 array([8, 8, 1, ..., 2, 7, 4], dtype=int64),
 array([1, 1, 1, ..., 8, 8, 8], dtype=int64),
 array([5, 5, 5, 6, 5, 6, 5, 5, 6, 5, 5, 5, 7, 5, 5, 5, 5, 5, 5, 7, 6, 5,
        6, 5, 5, 5, 5, 6, 5, 5, 5, 5, 5, 5, 5, 6, 5, 6, 5, 5, 5, 5, 6, 5,
        5, 5, 6, 6, 5, 5, 5, 6, 5, 6, 6, 5, 5, 5, 5, 5, 6, 5, 6, 6, 5, 5,
        6, 7, 6, 5, 6, 6, 5, 6, 6, 6, 5, 7, 6, 5, 3, 6, 6, 6, 7, 5, 6, 6,
        6, 6, 5, 6, 5, 7, 5, 6, 6, 7, 6, 6, 5, 8, 5, 6, 5, 7, 6

In [17]:
knn2 = Pipeline(
    [
        ('Scaler', StandardScaler()),
        ('Imputer', KNNImputer(n_neighbors=3, weights='distance')),
        ('KNN', KNeighborsClassifier(3, weights='distance',)),
    ]
)
test_model_on_all_data(knn)


c:\Users\Morri\Documents\Notebooks\ML\Project


c:\Users\Morri\Documents\Notebooks\ML\.venv\Lib\site-packages\sklearn\model_selection\_split.py:737: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(


dataset 1 weighted F1 score 5 fold cv:  [1.         0.96866002 0.89555556 0.91262626 0.9503876 ]
mean: 0.945
median: 0.969
std: 0.038
c:\Users\Morri\Documents\Notebooks\ML\Project
dataset 2 weighted F1 score 5 fold cv:  [0.93       0.89666667 0.84666667 0.58666667 0.83333333]
mean: 0.819
median: 0.897
std: 0.121
c:\Users\Morri\Documents\Notebooks\ML\Project
dataset 3 weighted F1 score 5 fold cv:  [0.27594564 0.24559458 0.28446243 0.26068096 0.26436301]
mean: 0.266
median: 0.276
std: 0.013
c:\Users\Morri\Documents\Notebooks\ML\Project
dataset 4 weighted F1 score 5 fold cv:  [0.8001186  0.65752045 0.64975154 0.56101407 0.42992551]
mean: 0.620
median: 0.658
std: 0.122
c:\Users\Morri\Documents\Notebooks\ML\Project
dataset 5 weighted F1 score 5 fold cv:  [0.41752807 0.48990801 0.50588167 0.48642254 0.53146975]
mean: 0.486
median: 0.506
std: 0.038


[array([2, 1, 1, 1, 1, 2, 1, 1, 3, 1, 3, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 4,
        3, 3, 4, 1, 5, 4, 1, 3, 1, 1, 4, 1, 1, 1, 1, 4, 3, 5, 3, 1, 4, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64),
 array([ 3, 11,  2,  4,  8,  8,  8,  8,  4,  8, 10, 11,  1,  1, 10,  8,  6,
         3,  8,  9,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4, 10, 11, 10, 11,
         4, 10, 11,  3,  3,  3,  3,  3,  3,  3,  2,  8,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  8,  8,  8,  8,  8,  8,  8,  8,
        11,  8, 10,  8,  8,  8], dtype=int64),
 array([8, 8, 1, ..., 2, 7, 4], dtype=int64),
 array([1, 1, 1, ..., 8, 8, 8], dtype=int64),
 array([5, 5, 5, 6, 5, 6, 5, 5, 6, 5, 5, 5, 7, 5, 5, 5, 5, 5, 5, 7, 6, 5,
        6, 5, 5, 5, 5, 6, 5, 5, 5, 5, 5, 5, 5, 6, 5, 6, 5, 5, 5, 5, 6, 5,
        5, 5, 6, 6, 5, 5, 5, 6, 5, 6, 6, 5, 5, 5, 5, 5, 6, 5, 6, 6, 5, 5,
        6, 7, 6, 5, 6, 6, 5, 6, 6, 6, 5, 7, 6, 5, 3, 6, 6, 6, 7, 5, 6, 6,
        6, 6, 5, 6, 5, 7, 5, 6, 6, 7, 6, 6, 5, 8, 5, 6, 5, 7, 6

In [18]:
# print("Missing value count:",  train.isna().sum().sum())
# print("Number of categories:",(len(target[0].unique())))

In [20]:
# random forest
clf = Pipeline([
    ('Scaler', StandardScaler()),
    ('imputation', KNNImputer(n_neighbors=3, weights='distance')),

    ('classification', RandomForestClassifier(
          # max_depth=4,
          max_features="log2",
          bootstrap=True,
          # max_samples=1000,
          n_jobs=-1,
          class_weight="balanced_subsample",
          # warm_start=True,
          random_state=51
          ))
])
test_model_on_all_data(clf)


c:\Users\Morri\Documents\Notebooks\ML\Project


c:\Users\Morri\Documents\Notebooks\ML\.venv\Lib\site-packages\sklearn\model_selection\_split.py:737: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(


dataset 1 weighted F1 score 5 fold cv:  [0.82222222 0.85319149 0.847343   0.85333333 0.85333333]
mean: 0.846
median: 0.853
std: 0.012
c:\Users\Morri\Documents\Notebooks\ML\Project
dataset 2 weighted F1 score 5 fold cv:  [0.93       0.855      0.89333333 0.7452381  0.8752381 ]
mean: 0.860
median: 0.893
std: 0.062
c:\Users\Morri\Documents\Notebooks\ML\Project
dataset 3 weighted F1 score 5 fold cv:  [0.29905412 0.28003981 0.31143939 0.2990342  0.29933837]
mean: 0.298
median: 0.299
std: 0.010
c:\Users\Morri\Documents\Notebooks\ML\Project
dataset 4 weighted F1 score 5 fold cv:  [0.82856483 0.75930685 0.72947445 0.75017846 0.50457118]
mean: 0.714
median: 0.759
std: 0.110
c:\Users\Morri\Documents\Notebooks\ML\Project
dataset 5 weighted F1 score 5 fold cv:  [0.50908401 0.62008477 0.5963108  0.55818125 0.59032518]
mean: 0.575
median: 0.596
std: 0.038


[array([2, 1, 1, 1, 1, 2, 1, 1, 3, 2, 3, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 4,
        1, 1, 4, 1, 1, 4, 1, 1, 1, 1, 4, 1, 1, 1, 1, 4, 3, 1, 1, 1, 4, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64),
 array([ 2, 11, 10,  4,  8,  4,  8,  8,  4,  3,  2, 11,  1,  1,  2,  3, 10,
         3,  8,  3,  4,  4,  4,  4,  4,  5,  4,  5,  5,  4, 10, 11, 11, 11,
         8, 10, 11,  3,  8,  3,  3,  3,  3,  3,  3,  3,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  8,  8,  8,  8, 11,  8,  8,  8,
         8,  8,  3,  8,  8,  8], dtype=int64),
 array([9, 8, 1, ..., 2, 7, 5], dtype=int64),
 array([1, 1, 1, ..., 8, 8, 8], dtype=int64),
 array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 5, 5, 5, 5, 5, 5, 6, 6, 5,
        6, 5, 5, 5, 5, 6, 5, 5, 5, 5, 5, 5, 5, 6, 5, 6, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 6, 5, 5, 5, 6, 5, 5, 6, 5, 5, 5, 5, 5, 5, 5, 5, 6, 5, 5,
        5, 6, 5, 5, 5, 6, 5, 6, 6, 6, 5, 7, 6, 5, 5, 5, 6, 6, 7, 5, 6, 6,
        6, 6, 5, 6, 5, 7, 5, 6, 6, 6, 6, 6, 7, 6, 7, 6, 5, 6, 6

In [23]:
# find optimal components for each dataset
opt_components = []
fig, axes = plt.subplots(5,1, sharex=False)
fig.set_size_inches(5,20)
for i in range(1,6):
    train, target, test = read_classification_dataset(i)
    X, y = train.values, target.values.flatten()
    n = min(train.shape)
    model = Pipeline([
      ('Scaler', StandardScaler()),
      ('imputation', KNNImputer(n_neighbors=3, weights='distance')),
      ("PCA", PCA(n_components=n))
    ])
    pca = model.fit_transform(train)

    pca_evr = (model.named_steps["PCA"].explained_variance_ratio_)



    pca_evr = np.concatenate((np.zeros(1), pca_evr))
    indx, cum_evr  = np.arange(n+1), np.cumsum(pca_evr)
    kneedle = KneeLocator(indx, cum_evr, direction='increasing', curve='concave', S=1.0, interp_method='polynomial', online=True)
    print(kneedle.knee)
    opt_components.append(kneedle.knee)
    axes[i-1].plot(list(range(n+1)),np.cumsum(pca_evr), color = 'black')
    axes[i-1].vlines(kneedle.knee, 0,1,'b', ':')
    axes[i-1].set_xlabel('Number of components')
    axes[i-1].set_ylabel('Cumulative explained variance')
    # axes[i-1].set_title("PCA - Cumulative Explained Variance Ratio")

    plt.grid()
print(opt_components)


In [22]:
# clf = LassoCV().fit(X, y)
# importance = np.abs(clf.coef_)
# idx_third = importance.argsort()[-3]
# threshold = importance[idx_third] + 0.01

# idx_features = (-importance).argsort()[:2]
# # name_features = np.array(feature_names)[idx_features]
# print('Selected features: {}'.format(idx_features))

# sfm = SelectFromModel(clf, threshold=threshold)
# sfm.fit(X, y)
# X_transform = sfm.transform(X)

# n_features = sfm.transform(X).shape[1]